<div class="row">
	<div class="col-xs-6">
		<a href="#" class="thumbnail">
			<img src="/images/download.png" alt="My analyser" class="img-circle">
		</a>
	</div>	
	<div class="col-xs-6">
		<a href="#" class="thumbnail">
			<img src="/images/download.png" alt="My analyser" class="img-circle">
		</a>
	</div>
</div>	
<div class="list-group">
  <a href="#" class="list-group-item">
	<h4 class="list-group-item-heading">My analyser</h4>
	<p class="list-group-item-text">details of my own</p>
  </a>
</div>
<div class="list-group">
  <a href="#" class="list-group-item">
	<h4 class="list-group-item-heading">Client analyser</h4>
	<p class="list-group-item-text">details of my clients analysis</p>
  </a>
</div>
<div class="row">
	<div class="col-xs-6">
		<a href="#" class="thumbnail">
		  <img src="/images/download.png" alt="">
		</a>
	</div>
	<div class="col-xs-6">
		<a href="#" class="thumbnail">
		  <img src="/images/download.png" alt="">
		</a>
	</div>
</div>