<!DOCTYPE html>
<!-- saved from url=(0040)http://getbootstrap.com/examples/signin/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="http://getbootstrap.com/docs-assets/ico/favicon.png">

    <title>Forget my password</title>

    <!-- Bootstrap core CSS -->
<!--     <link href="http://getbootstrap.com/dist/css/bootstrap.css" rel="stylesheet"> -->
	<link href="<?php echo $this->config['domain']['url'].'/'; ?>lib/bootstrap3.0/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="<?php echo $this->config['domain']['url'].'/'; ?>lib/font-awesome/4.0.3/css/font-awesome.css">
	
	<!--[if IE 7]>
	<link rel="stylesheet" href="<?php echo $this->config['domain']['url'].'/'; ?>lib/font-awesome/css/font-awesome-ie7.min.css" />
	<![endif]-->
    <!-- Custom styles for this template -->
<!--     <link href="http://getbootstrap.com/examples/signin/signin.css" rel="stylesheet"> -->
	<link rel="stylesheet" href="<?php echo $this->config['domain']['url'].'/'.$this->config['template']['path'].'/'.$this->config['template']['name']; ?>/css/signin.css" type="text/css" media="all" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  	<div align='center' class='flag_div'>
  		<a href='#'><img src='<?php echo $this->config['domain']['url'].'/'.$this->config['template']['path'].'/'.$this->config['template']['name']; ?>/images/sweden_flag.gif' class='img-thumbnail flag' alt='swedish' title='Swedish' ></a><a href=''><img src='<?php echo $this->config['domain']['url'].'/'.$this->config['template']['path'].'/'.$this->config['template']['name']; ?>/images/uk_flag.gif' class='img-thumbnail flag' alt='English' title='English'></a>
  	</div>
	</nav>
    <div class="container">
      <h1 align="center">
      	<a href="<?php echo $this->config['domain']['url']; ?>" title="Powered by <?php echo $this->config['domain']['name']; ?>"><img class='img-responsive img-center logo' 
      		src='<?php echo $this->config['domain']['url'].'/'.$this->config['template']['path'].'/'.$this->config['template']['name']; ?>/images/mylogo.jpg'   /></a></h1>
	  <div id="login_error" style="display:none"></div> <!-- error message shows here -->
      <noscript>
      	<div class='alert alert-warning middle_div'>
      		<i class='fa fa-warning'></i> This website needs JavaScript to work, you must enable JavaScript in your browser. <a href='<?php echo $this->link('page/enablejavascript'); ?>'>This link will help you how to do that.</a>
      	</div>
      </noscript>
      <form class="form-signin" role="form" action="<?php echo $this->link('home/index'); ?>" method="post">
        <div class="form-group">
	    	<label for="exampleInputEmail1">Email address</label>
		    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email" required>
	  	</div>
  		<div class="form-group">
	    	<label> Answer : </label>
	    	
	    	<?php
				$a = rand(0, 9);
				$b = rand(0, 9);
				echo $a ."+".$b." = ";
				echo "<input type='hidden' value='$a-$b' name='math'>";
			?>
			<input name="ans" class="ans" maxlength='2' tabindex="2" type="text"  required />
        </div>	
        <div class="form-group">
	        <p><div class="col-xs-6">
	        	<a class="btn btn-lg btn-default btn-block" href="<?php echo $this->link('login/index'); ?>"><i class="fa fa-times-circle"></i> Cancel</a>
	        </div>
	        <div class="col-xs-6">
	         	<button class="btn btn-lg btn-primary btn-block" type="submit"><i class="fa fa-envelope"></i> Submit</button> 
	        </div>
	        <div class='blankrow'>&nbsp;</div>
        </div>
      </form>
    </div> <!-- /container -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

</body></html>