<!DOCTYPE html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="bootstrap3/css/bootstrap.min.css" >
		<link rel="stylesheet" href="css/styles.css" >
	</head>
	<body>
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-navbar-collapse-1">
				  <span class="sr-only">Toggle navigation</span>
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#"><img src="images/mylogo.jpg" class="logo"></a>
			</div>
			<div class="collapse navbar-collapse" id="menu-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li class="active"><a href="#">My profile</a></li>
					<li><a href="#">Clients</a></li>
					<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
					<ul class="dropdown-menu">
					  <li><a href="#">Action</a></li>
					  <li><a href="#">Another action</a></li>
					  <li><a href="#">Something else here</a></li>
					  <li class="divider"></li>
					  <li><a href="#">Separated link</a></li>
					</ul>
				  </li>
				</ul>		
			</div>
		</nav>
		<div class="container hundred">
			<div class="row">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li><a href="#">Library</a></li>
				  <li class="active">Data</li>
				</ol>
				
			</div>	
		</div>
		<div class="container">
			<div class="row">
				<div class="col-xs-6">
					<a href="#" class="thumbnail">
						<img src="images/download.png" alt="My analyser" class="img-circle">
					</a>
				</div>	
				<div class="col-xs-6">
					<a href="#" class="thumbnail">
						<img src="images/download.png" alt="My analyser" class="img-circle">
					</a>
				</div>
			</div>	
			<div class="list-group">
			  <a href="#" class="list-group-item">
				<h4 class="list-group-item-heading">My analyser</h4>
				<p class="list-group-item-text">details of my own</p>
			  </a>
			</div>
			<div class="list-group">
			  <a href="#" class="list-group-item">
				<h4 class="list-group-item-heading">Client analyser</h4>
				<p class="list-group-item-text">details of my clients analysis</p>
			  </a>
			</div>
			<div class="row">
				<div class="col-xs-6">
					<a href="#" class="thumbnail">
					  <img src="images/download.png" alt="">
					</a>
				</div>
				<div class="col-xs-6">
					<a href="#" class="thumbnail">
					  <img src="images/download.png" alt="">
					</a>
				</div>
			</div>
		</div>
		<script src="jquery/jquery-1.10.2.min.js"></script>
		<script src="bootstrap3/js/bootstrap.min.js"></script>
	</body>
</html>
